<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class BadgeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $badges = [
            // ========== ÖZEL ROZETLER (SPECIAL) ==========
            [
                'name' => 'Topluluğa İlk Adım',
                'slug' => 'first-step',
                'description' => 'Profilini tamamladın!',
                'icon' => 'star',
                'category' => 'special',
                'rarity' => 'common',
                'xp_required' => 50,
                'sort_order' => 1,
            ],
            [
                'name' => 'Beta Kullanıcısı',
                'slug' => 'beta-user',
                'description' => 'İlk 100 üye arasındasın!',
                'icon' => 'badge-check',
                'category' => 'special',
                'rarity' => 'legendary',
                'is_hidden' => true,
                'xp_required' => 0,
                'sort_order' => 2,
            ],
            [
                'name' => 'Kurucu Üye',
                'slug' => 'founder-member',
                'description' => 'İlk 1000 üye arasındasın',
                'icon' => 'gem',
                'category' => 'special',
                'rarity' => 'epic',
                'xp_required' => 0,
                'sort_order' => 3,
            ],
            [
                'name' => 'Efsane Katkıcı',
                'slug' => 'legendary-contributor',
                'description' => 'Topluluğa olağanüstü katkıda bulundun',
                'icon' => 'award',
                'category' => 'special',
                'rarity' => 'legendary',
                'is_hidden' => true,
                'xp_required' => 0,
                'sort_order' => 4,
            ],
            [
                'name' => 'Topluluk Kahramanı',
                'slug' => 'community-hero',
                'description' => 'Admin tarafından özel olarak verildi',
                'icon' => 'heart',
                'category' => 'special',
                'rarity' => 'legendary',
                'is_hidden' => true,
                'xp_required' => 0,
                'sort_order' => 5,
            ],

            // ========== OYUN BAŞARILARI (GAMEPLAY) ==========
            [
                'name' => 'Ace Oyuncu',
                'slug' => 'ace-player',
                'description' => 'Ace rank\'e ulaştın',
                'icon' => 'trending-up',
                'category' => 'gameplay',
                'rarity' => 'epic',
                'xp_required' => 100,
                'sort_order' => 10,
            ],
            [
                'name' => 'Conqueror Efsanesi',
                'slug' => 'conqueror-legend',
                'description' => 'Conqueror rank\'e ulaştın',
                'icon' => 'crown',
                'category' => 'gameplay',
                'rarity' => 'legendary',
                'xp_required' => 200,
                'sort_order' => 11,
            ],
            [
                'name' => 'TPP Uzmanı',
                'slug' => 'tpp-expert',
                'description' => '50+ TPP maç oynadın',
                'icon' => 'eye',
                'category' => 'gameplay',
                'rarity' => 'rare',
                'xp_required' => 50,
                'sort_order' => 12,
            ],
            [
                'name' => 'FPP Ustası',
                'slug' => 'fpp-master',
                'description' => '50+ FPP maç oynadın',
                'icon' => 'crosshair',
                'category' => 'gameplay',
                'rarity' => 'rare',
                'xp_required' => 50,
                'sort_order' => 13,
            ],
            [
                'name' => 'Solo Savaşçı',
                'slug' => 'solo-warrior',
                'description' => '100+ solo maç oynadın',
                'icon' => 'user',
                'category' => 'gameplay',
                'rarity' => 'rare',
                'xp_required' => 75,
                'sort_order' => 14,
            ],
            [
                'name' => 'Squad Lideri',
                'slug' => 'squad-leader',
                'description' => '100+ squad maç oynadın',
                'icon' => 'users',
                'category' => 'gameplay',
                'rarity' => 'rare',
                'xp_required' => 75,
                'sort_order' => 15,
            ],

            // ========== SOSYAL ROZETLER (SOCIAL) ==========
            [
                'name' => 'İlk Arkadaşını Buldu',
                'slug' => 'first-friend',
                'description' => 'İlk arkadaşını ekledin',
                'icon' => 'user-plus',
                'category' => 'social',
                'rarity' => 'common',
                'xp_required' => 20,
                'sort_order' => 20,
            ],
            [
                'name' => 'Sosyal Kelebek',
                'slug' => 'social-butterfly',
                'description' => '50+ arkadaş edindin',
                'icon' => 'users',
                'category' => 'social',
                'rarity' => 'epic',
                'xp_required' => 100,
                'sort_order' => 21,
            ],
            [
                'name' => 'Popüler Oyuncu',
                'slug' => 'popular-player',
                'description' => '100+ arkadaş edindin',
                'icon' => 'star',
                'category' => 'social',
                'rarity' => 'legendary',
                'xp_required' => 150,
                'sort_order' => 22,
            ],
            [
                'name' => 'Mesaj Makinesi',
                'slug' => 'message-machine',
                'description' => '1000+ mesaj gönderdin',
                'icon' => 'message-circle',
                'category' => 'social',
                'rarity' => 'rare',
                'xp_required' => 100,
                'sort_order' => 23,
            ],
            [
                'name' => 'Yorum Ustası',
                'slug' => 'comment-master',
                'description' => '100+ yorum yaptın',
                'icon' => 'message-square',
                'category' => 'social',
                'rarity' => 'rare',
                'xp_required' => 75,
                'sort_order' => 24,
            ],
            [
                'name' => 'Beğeni Kralı',
                'slug' => 'like-king',
                'description' => '500+ beğeni aldın',
                'icon' => 'thumbs-up',
                'category' => 'social',
                'rarity' => 'epic',
                'xp_required' => 100,
                'sort_order' => 25,
            ],

            // ========== İÇERİK ÜRETİMİ (CONTENT) ==========
            [
                'name' => 'İlk İlanını Açtı',
                'slug' => 'first-lfg',
                'description' => 'İlk LFG ilanını oluşturdun',
                'icon' => 'megaphone',
                'category' => 'content',
                'rarity' => 'common',
                'xp_required' => 30,
                'sort_order' => 30,
            ],
            [
                'name' => 'Aktif İlan Sahibi',
                'slug' => 'active-poster',
                'description' => '25+ LFG ilanı oluşturdun',
                'icon' => 'file-text',
                'category' => 'content',
                'rarity' => 'rare',
                'xp_required' => 75,
                'sort_order' => 31,
            ],
            [
                'name' => 'Klan Kurucusu',
                'slug' => 'clan-founder',
                'description' => 'İlk klanını kurdun',
                'icon' => 'shield',
                'category' => 'content',
                'rarity' => 'epic',
                'xp_required' => 100,
                'sort_order' => 32,
            ],
            [
                'name' => 'Klan Lideri',
                'slug' => 'clan-leader',
                'description' => 'Klanın 25+ üyeye ulaştı',
                'icon' => 'shield-check',
                'category' => 'content',
                'rarity' => 'epic',
                'xp_required' => 150,
                'sort_order' => 33,
            ],
            [
                'name' => 'Rehber Yazarı',
                'slug' => 'guide-writer',
                'description' => 'İlk rehberini yazdın',
                'icon' => 'book',
                'category' => 'content',
                'rarity' => 'common',
                'xp_required' => 40,
                'sort_order' => 34,
            ],
            [
                'name' => 'Üretken Yazar',
                'slug' => 'productive-writer',
                'description' => '10+ rehber yazdın',
                'icon' => 'book-open',
                'category' => 'content',
                'rarity' => 'rare',
                'xp_required' => 150,
                'sort_order' => 35,
            ],
            [
                'name' => 'Popüler Rehber Yazarı',
                'slug' => 'popular-guide-writer',
                'description' => 'Rehberlerin 1000+ görüntülenme aldı',
                'icon' => 'trending-up',
                'category' => 'content',
                'rarity' => 'epic',
                'xp_required' => 200,
                'sort_order' => 36,
            ],
            [
                'name' => 'Cihaz Uzmanı',
                'slug' => 'device-expert',
                'description' => 'Cihaz & sens bilgilerini paylaştın',
                'icon' => 'smartphone',
                'category' => 'content',
                'rarity' => 'common',
                'xp_required' => 25,
                'sort_order' => 37,
            ],
            [
                'name' => 'Takım Kurucusu',
                'slug' => 'squad-founder',
                'description' => 'İlk takımını kurdun',
                'icon' => 'users',
                'category' => 'content',
                'rarity' => 'rare',
                'xp_required' => 50,
                'sort_order' => 38,
            ],
            [
                'name' => 'Etkinlik Organizatörü',
                'slug' => 'event-organizer',
                'description' => 'İlk turnuvayı düzenledin',
                'icon' => 'calendar',
                'category' => 'content',
                'rarity' => 'epic',
                'xp_required' => 100,
                'sort_order' => 39,
            ],

            // ========== AKTİVİTE ROZETLER (ACTIVITY) ==========
            [
                'name' => '7 Günlük Seri',
                'slug' => 'week-streak',
                'description' => '7 gün üst üste giriş yaptın',
                'icon' => 'calendar',
                'category' => 'activity',
                'rarity' => 'rare',
                'xp_required' => 50,
                'sort_order' => 40,
            ],
            [
                'name' => '30 Günlük Seri',
                'slug' => 'month-streak',
                'description' => '30 gün üst üste giriş yaptın',
                'icon' => 'calendar-check',
                'category' => 'activity',
                'rarity' => 'epic',
                'xp_required' => 150,
                'sort_order' => 41,
            ],
            [
                'name' => '100 Günlük Seri',
                'slug' => 'hundred-day-streak',
                'description' => '100 gün üst üste giriş yaptın',
                'icon' => 'zap',
                'category' => 'activity',
                'rarity' => 'legendary',
                'xp_required' => 500,
                'sort_order' => 42,
            ],
            [
                'name' => 'Sabah Kuşu',
                'slug' => 'early-bird',
                'description' => 'Sabah 6-9 arası 30 kez giriş yaptın',
                'icon' => 'sunrise',
                'category' => 'activity',
                'rarity' => 'rare',
                'is_hidden' => true,
                'xp_required' => 50,
                'sort_order' => 43,
            ],
            [
                'name' => 'Gece Baykuşu',
                'slug' => 'night-owl',
                'description' => 'Gece 00-03 arası 30 kez giriş yaptın',
                'icon' => 'moon',
                'category' => 'activity',
                'rarity' => 'rare',
                'is_hidden' => true,
                'xp_required' => 50,
                'sort_order' => 44,
            ],
            [
                'name' => 'Hafta Sonu Savaşçısı',
                'slug' => 'weekend-warrior',
                'description' => '20+ hafta sonu girişi yaptın',
                'icon' => 'coffee',
                'category' => 'activity',
                'rarity' => 'rare',
                'xp_required' => 40,
                'sort_order' => 45,
            ],
            [
                'name' => 'Aktif Oyuncu',
                'slug' => 'active-player',
                'description' => '300 XP topladın',
                'icon' => 'fire',
                'category' => 'activity',
                'rarity' => 'rare',
                'xp_required' => 300,
                'sort_order' => 46,
            ],
            [
                'name' => 'Topluluk Çekirdeği',
                'slug' => 'community-core',
                'description' => '600 XP topladın',
                'icon' => 'trophy',
                'category' => 'activity',
                'rarity' => 'epic',
                'xp_required' => 600,
                'sort_order' => 47,
            ],
            [
                'name' => 'Efsane Oyuncu',
                'slug' => 'legendary-player',
                'description' => '1500 XP topladın',
                'icon' => 'award',
                'category' => 'activity',
                'rarity' => 'legendary',
                'xp_required' => 1500,
                'sort_order' => 48,
            ],
            [
                'name' => 'Turnuva Şampiyonu',
                'slug' => 'tournament-champion',
                'description' => 'Bir turnuvayı kazandın',
                'icon' => 'trophy',
                'category' => 'activity',
                'rarity' => 'legendary',
                'xp_required' => 200,
                'sort_order' => 49,
            ],

            // ========== MODERASYON ROZETLER (MODERATION) ==========
            [
                'name' => 'İlk Rapor',
                'slug' => 'first-report',
                'description' => 'İlk spam raporunu yaptın',
                'icon' => 'flag',
                'category' => 'moderation',
                'rarity' => 'common',
                'xp_required' => 10,
                'sort_order' => 50,
            ],
            [
                'name' => 'Topluluk Koruyucusu',
                'slug' => 'community-guardian',
                'description' => '10+ doğru rapor yaptın',
                'icon' => 'shield',
                'category' => 'moderation',
                'rarity' => 'epic',
                'xp_required' => 100,
                'sort_order' => 51,
            ],
            [
                'name' => 'Yardım Meleği',
                'slug' => 'help-angel',
                'description' => '50+ yardımcı yanıt verdin',
                'icon' => 'life-buoy',
                'category' => 'moderation',
                'rarity' => 'rare',
                'xp_required' => 75,
                'sort_order' => 52,
            ],
        ];

        foreach ($badges as $badge) {
            \App\Models\Badge::updateOrCreate(
                ['slug' => $badge['slug']],
                $badge
            );
        }
    }
}
